import{a as g,S as y,i as d}from"./assets/vendor-cec502ba.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const p={PIXABAY:{PATH:"https://pixabay.com/api/",KEY:"43768517-7da35ee1e4b58521b64ca0165",PER_PAGE:15}},b=async(t,r=1)=>await g.get(p.PIXABAY.PATH,{params:{key:p.PIXABAY.KEY,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:p.PIXABAY.PER_PAGE}}),P=t=>`
    <a href="${t.largeImageURL}" class="item">
      <img src="${t.webformatURL}" alt="" alt="${t.tags}"/>
      <div class="data">
        <p><b>Likes</b> <span>${t.likes}</span></p>
        <p><b>Views</b> <span>${t.views}</span></p>
        <p><b>Comments</b> <span>${t.comments}</span></p>
        <p><b>Downloads</b> <span>${t.downloads}</span></p>
      </div>
    </a>
  `;const m=document.querySelector("form.form-search"),i=document.querySelector(".gallery"),a=document.querySelector(".actionShowMoreImages"),h=document.querySelector(".field-input_search"),L=new y(".gallery a",{});let c=1,u=1;function f(t,r=!0){r&&(c=1),!(u<c)&&b(t,c).then(n=>{const{hits:l,totalHits:e}=n.data;i.classList.remove("is-load");const s=[];if(e===0)a.classList.add("is-hidden"),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",class:"error",color:"white"}),u=1,m.reset();else{if(u=Math.ceil(e/p.PIXABAY.PER_PAGE),c+=1,u<c){a.classList.add("is-hidden"),d.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"error",color:"white"});return}if(l.forEach(o=>{s.push(P(o))}),r)i.innerHTML=s.join("");else{i.insertAdjacentHTML("beforeend",s.join(""));const o=i.querySelector(".item");window.scrollBy({top:o.getBoundingClientRect().height*2,behavior:"smooth"})}a.classList.remove("is-hidden"),L.refresh()}}).catch(n=>{console.log(n)})}m&&m.addEventListener("submit",t=>{t.preventDefault(),a.classList.add("is-hidden");const r=h.value;r?(i.innerHTML="",i.classList.add("is-load"),f(r)):d.error({message:"Please enter a search term",position:"topRight",class:"error",color:"white"})});a&&a.addEventListener("click",()=>{const t=h.value;f(t,!1)});
//# sourceMappingURL=commonHelpers.js.map
