import{a as g,S as y,i as p}from"./assets/vendor-cec502ba.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&d(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const u={PIXABAY:{PATH:"https://pixabay.com/api/",KEY:"43768517-7da35ee1e4b58521b64ca0165",PER_PAGE:15}},b=async(t,r=1)=>await g.get(u.PIXABAY.PATH,{params:{key:u.PIXABAY.KEY,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:u.PIXABAY.PER_PAGE}}),L=t=>`
    <a href="${t.largeImageURL}" class="item">
      <img src="${t.webformatURL}" alt="" alt="${t.tags}"/>
      <div class="data">
        <p><b>Likes</b> <span>${t.likes}</span></p>
        <p><b>Views</b> <span>${t.views}</span></p>
        <p><b>Comments</b> <span>${t.comments}</span></p>
        <p><b>Downloads</b> <span>${t.downloads}</span></p>
      </div>
    </a>
  `;const h=document.querySelector("form.form-search"),a=document.querySelector(".gallery"),i=document.querySelector(".actionShowMoreImages"),m=document.querySelector(".field-input_search"),P=new y(".gallery a",{});let c=1,l=1;function f(t,r=!0){r&&(c=1),b(t,c).then(n=>{const{hits:d,totalHits:e}=n.data;a.classList.remove("is-load");const s=[];if(e===0){i.classList.add("is-hidden"),p.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",class:"error",color:"white"}),l=1,h.reset();return}if(l=Math.ceil(e/u.PIXABAY.PER_PAGE),l<c){i.classList.add("is-hidden"),p.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"error",color:"white"});return}if(c+=1,d.forEach(o=>{s.push(L(o))}),r)a.innerHTML=s.join("");else{a.insertAdjacentHTML("beforeend",s.join(""));const o=a.querySelector(".item");window.scrollBy({top:o.getBoundingClientRect().height*2,behavior:"smooth"})}l>1&&i.classList.remove("is-hidden"),c>l&&i.classList.add("is-hidden"),P.refresh()}).catch(n=>{console.log(n)})}h&&h.addEventListener("submit",t=>{t.preventDefault(),i.classList.add("is-hidden");const r=m.value;r?(a.innerHTML="",a.classList.add("is-load"),f(r)):p.error({message:"Please enter a search term",position:"topRight",class:"error",color:"white"})});i&&i.addEventListener("click",()=>{const t=m.value;f(t,!1)});
//# sourceMappingURL=commonHelpers.js.map
