import{a as g,S as y,i as d}from"./assets/vendor-cec502ba.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&c(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const p={PIXABAY:{PATH:"https://pixabay.com/api/",KEY:"43768517-7da35ee1e4b58521b64ca0165",PER_PAGE:15}},b=async(t,s=1)=>await g.get(p.PIXABAY.PATH,{params:{key:p.PIXABAY.KEY,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:p.PIXABAY.PER_PAGE}}),P=t=>`
    <a href="${t.largeImageURL}" class="item">
      <img src="${t.webformatURL}" alt="" alt="${t.tags}"/>
      <div class="data">
        <p><b>Likes</b> <span>${t.likes}</span></p>
        <p><b>Views</b> <span>${t.views}</span></p>
        <p><b>Comments</b> <span>${t.comments}</span></p>
        <p><b>Downloads</b> <span>${t.downloads}</span></p>
      </div>
    </a>
  `;const m=document.querySelector("form.form-search"),i=document.querySelector(".gallery"),a=document.querySelector(".actionShowMoreImages"),h=document.querySelector(".field-input_search"),L=new y(".gallery a",{});let l=1,u=1;function f(t,s=!0){s&&(l=1),b(t,l).then(n=>{const{hits:c,totalHits:e}=n.data;i.classList.remove("is-load");const r=[];if(e===0){a.classList.add("is-hidden"),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",class:"error",color:"white"}),u=1,m.reset();return}if(u=Math.ceil(e/p.PIXABAY.PER_PAGE),u<l){a.classList.add("is-hidden"),d.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"error",color:"white"});return}if(l+=1,c.forEach(o=>{r.push(P(o))}),s)i.innerHTML=r.join("");else{i.insertAdjacentHTML("beforeend",r.join(""));const o=i.querySelector(".item");window.scrollBy({top:o.getBoundingClientRect().height*2,behavior:"smooth"})}u>1&&a.classList.remove("is-hidden"),L.refresh()}).catch(n=>{console.log(n)})}m&&m.addEventListener("submit",t=>{t.preventDefault(),a.classList.add("is-hidden");const s=h.value;s?(i.innerHTML="",i.classList.add("is-load"),f(s)):d.error({message:"Please enter a search term",position:"topRight",class:"error",color:"white"})});a&&a.addEventListener("click",()=>{const t=h.value;f(t,!1)});
//# sourceMappingURL=commonHelpers.js.map
